name: Go CI and Release

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    uses: github.com/TheCacophonyProject/github-actions-templates/.github/workflows/ci.yml@main
    with:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
